name: Build and publish coraos-zsh-config

on:
  push:
    branches: [main]
    paths:
      - 'coraos-zsh-config/PKGBUILD'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/builder-workflow.yaml
    with:
      pkgdir: coraos-zsh-config
      keep_versions: 2
    secrets: inherit
