name: Build and publish coraos-zsh-config

on:
  push:
    branches: [main]
    paths:
      - "coraos-zsh-config/PKGBUILD"
  workflow_dispatch:

jobs:
  build:
    uses: Cora-Linux-Distro/CI-TEMPLATES/.github/workflows/build-simple.yml@main
    with:
      pkgdir: coraos-zsh-config
      keep_versions: 2
    secrets: inherit
